config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'profile/:id', to: 'persons#profile', as: 'profile'
    get '/moon', to: 'application#moon', as: 'moon'
    get '/sun', to: 'application#sun', as: 'sun'
    get '/rating_sort', to: 'projects#rating_sort', as: 'rating_sort'
    get '/created_at_sort', to: 'projects#created_at_sort', as: 'created_at_sort'
    get '/updated_at_sort', to: 'projects#updated_at_sort', as: 'updated_at_sort'
    get '/profile/:id/give_permission', to: 'persons#give_permission', as: 'give_permission'
    get '/profile/:id/take_away_permission', to: 'persons#take_away_permission', as: 'take_away_permission'
    get '/profile/:id/ban', to: 'persons#ban', as: 'ban'
    get '/profile/:id/unban', to: 'persons#unban', as: 'unban'
    get '/profile/:id/ban_page', to: 'persons#ban_page', as: 'ban_page'
    delete '/profile/:id', to: 'persons#delete_user'
    get '/profile/:id/projects/new', to: 'persons#new_user_project', as: 'user_project_new'
    post '/profile/:id/projects', to: 'persons#create_user_project'
    get '/bonus/:bonus_id/user_bonus/create', to: 'user_bonuses#create', as: 'user_bonus_create'
    get 'projects/:project_id/transaction/new', to: 'transactions#new', as: 'new_project_transaction'
    post '/projects/:project_id/transactions', to: 'transactions#create'
    get '/add_balance/new', to: 'add_balances#new', as: 'new_add_balance'
    post '/add_balance/create', to: 'add_balances#create'
    get '/tagged', to: "projects#tagged", as: 'tagged'
    devise_for :users, skip: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }




    resources :projects do
    	resources :comments
      resources :reviews
      resources :events
    end

    resources :comments do
    	resources :likes
    end
    
    resources :project_images
    resources :bonuses


    root 'projects#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :project
	has_many :likes, dependent: :destroy
	validates :body, presence:true, allow_blank:false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  	before_action :authenticate_user!, only: [:create, :edit, :update]
	before_action :load_entities
	before_action :require_permission, only:[:edit, :update, :destroy]


	def index
		load_comments
		render 'create.js'
	end

	def create
			@comment = @user.comments.new(comment_params)
	   		@comment.save
	   		load_comments
      	#redirect_back(fallback_location: project_path(@comment.project))
	end

	def edit
		@comment = Comment.find(params[:id])
		@project = @comment.project
	end

	def update
		@comment = Comment.find(params[:id])
		@project = @comment.project
		if @comment.update_attributes(comment_params)
			flash[:success] = t("flash.comments.update")
			redirect_to project_path(@project)
		else
			render 'edit'
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
	end

	private

	def comment_params
		params.slice(:project_id).merge(params.require(:comment).permit(:body)).permit!
	end

	def load_entities
		@user = current_user
	end

	def load_comments
		@comments = Comment.where(project_id: params[:project_id]).order("id desc").limit(10).reverse
	end

	def require_permission
		if @user.admin != true
	      if current_user != Comment.find(params[:id]).user
	        redirect_to project_path(Comment.find(params[:id]).project)
	      end
	  	end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment|%>
	<p class="mb-1 user_comments">
		<%= "#{comment.created_at.strftime("%d/%m/%y %I:%M %p")} #{comment.user.username} : #{comment.body}" %>
		<%if user_signed_in?%>
			<% if @user.id == comment.user_id || user_admin?(@user)%>
				<%= link_to t("project.comments.edit"), edit_comment_path(comment) %>
				<%= link_to t("project.comments.destroy"), comment, data: {confirm: "#{t("project.comments.confirmation")}"}, method: :delete %>
			<%end%>
			<% pre_like = comment.likes.find {|like| like.user_id == current_user.id } %>
			<%if pre_like%>
				<%= button_to t("project.comments.unlike"), comment_like_path(comment, pre_like), method: :delete %>
			<%else%>
				<%= button_to t("project.comments.like"), comment_likes_path(comment), method: :post %>
			<%end%>
		<%end%>

		<%if comment.likes.any?%>
			<%= "#{comment.likes.count}" %> <%= comment.likes.count == 1 ? t("project.comments.one_like") : t("project.comments.many_likes")%>
		<%end%>
	</p>
	<hr>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment, url:yield(:comment_form_url), remote: true) do |f| %>
	<%= f.input :body, input_html: {style: 'resize: none; height:100px;'} %>
	<%= f.button :submit, t("project.comments.submit"), class:"btn btn-primary" %>
<% end %>

app/views/comments/create.js.erb
$('#comment_update').html("<%= j render partial: 'comments/comment' %>");

app/views/comments/edit.html.erb
<%provide(:comment_form_url, project_comment_path(@project))%>
<div class="comment-form">
	<h1><%= t("comment.edit_title") %></h1>
</div>
<hr>
<div class="comment-form">
	<%= render 'form' %>
</div>