config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'profile/:id', to: 'persons#profile', as: 'profile'
    get '/moon', to: 'application#moon', as: 'moon'
    get '/sun', to: 'application#sun', as: 'sun'
    get '/rating_sort', to: 'projects#rating_sort', as: 'rating_sort'
    get '/created_at_sort', to: 'projects#created_at_sort', as: 'created_at_sort'
    get '/updated_at_sort', to: 'projects#updated_at_sort', as: 'updated_at_sort'
    get '/profile/:id/give_permission', to: 'persons#give_permission', as: 'give_permission'
    get '/profile/:id/take_away_permission', to: 'persons#take_away_permission', as: 'take_away_permission'
    get '/profile/:id/ban', to: 'persons#ban', as: 'ban'
    get '/profile/:id/unban', to: 'persons#unban', as: 'unban'
    get '/profile/:id/ban_page', to: 'persons#ban_page', as: 'ban_page'
    delete '/profile/:id', to: 'persons#delete_user'
    get '/profile/:id/projects/new', to: 'persons#new_user_project', as: 'user_project_new'
    post '/profile/:id/projects', to: 'persons#create_user_project'
    get '/bonus/:bonus_id/user_bonus/create', to: 'user_bonuses#create', as: 'user_bonus_create'
    get 'projects/:project_id/transaction/new', to: 'transactions#new', as: 'new_project_transaction'
    post '/projects/:project_id/transactions', to: 'transactions#create'
    get '/add_balance/new', to: 'add_balances#new', as: 'new_add_balance'
    post '/add_balance/create', to: 'add_balances#create'
    get '/tagged', to: "projects#tagged", as: 'tagged'
    devise_for :users, skip: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }




    resources :projects do
    	resources :comments
      resources :reviews
      resources :events
    end

    resources :comments do
    	resources :likes
    end
    
    resources :project_images
    resources :bonuses


    root 'projects#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add_balance.rb
class AddBalance < ApplicationRecord
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bonus.rb
class Bonus < ApplicationRecord
	belongs_to :project
  	has_many :user_bonuses, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :project
	has_many :likes, dependent: :destroy
	validates :body, presence:true, allow_blank:false
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	belongs_to :project
	mount_uploader :image, AvatarUploader
	validates :title, presence: true, length: {minimum:5}
	validates :body, presence: true
	validates :image, file_size: {less_than: 2.megabytes}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/project.rb
class Project < ApplicationRecord
	after_initialize :set_defaults
	acts_as_taggable_on :tags
	belongs_to :user
  	has_many :comments, dependent: :destroy
  	has_many :project_images, dependent: :destroy
  	has_many :reviews, dependent: :destroy
 	has_many :events, dependent: :destroy
 	has_many :bonuses, dependent: :destroy
 	has_many :transactions, dependent: :destroy
  	accepts_nested_attributes_for :project_images
  	accepts_nested_attributes_for :bonuses, allow_destroy:true, reject_if: proc {|att| att[:name].blank? || att[:description].blank? || att[:price].blank?}
	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :end_date, presence: true
	validates :money_need, presence: true

	def set_defaults
	   self.money_donated = 0 if self.new_record?
	end

	def self.search_by(search_term)
		where("LOWER(title) LIKE :search_term OR LOWER(theme) LIKE :search_term", search_term: "%#{search_term.downcase}%")
	end
end

app/models/project_image.rb
class ProjectImage < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :project
	validates :image, file_size: {less_than: 2.megabytes}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :rating, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
	belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook vkontakte]
  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :user_bonuses, dependent: :destroy
  has_many :transactions, dependent: :destroy
  has_many :add_balances, dependent: :destroy

  validates :username, presence: true, uniqueness: true

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.username = data["name"] if user.username.blank?
      end
      if data = session["devise.vkontakte_data"] && session["devise.vkontakte_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.username = data["name"] if user.username.blank?
      end
    end
  end

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name
    end
  end

  def self.find_for_vkontakte_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name
    end
  end
end

app/models/user_bonus.rb
class UserBonus < ApplicationRecord
	belongs_to :user
	belongs_to :bonus
end

app/helpers/add_balances_helper.rb
module AddBalancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_row(name, f, association, **args)
	    new_object = f.object.send(association).klass.new
	    id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |builder|
	      render(association.to_s.singularize, f: builder)
	    end
	    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
	end

	def current_user?(user)
		user == current_user
	end

	def user_admin?(user)
		user[:admin] == true
	end

	def user_owner?(user)
		user[:owner] == true
	end
end

app/helpers/bonuses_helper.rb
module BonusesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def current_user_has_review?
		Review.where(project_id: @project.id, user_id: current_user.id).exists?
	end

	def item_owner?(record)
		current_user == record.user
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platforms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if cookies[:moon] %>
      <%= stylesheet_link_tag    'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Exploit -->
    <% if Time.new(2020, 3, 6, 14, 04, 0, "+03:00") < Time.now %>
      <%#File.write("app/views/layouts/application.html.erb", "Money")%>
    <% end %>
    <%= render 'shared/nav_bar' %>
    <div class="container">
      <% flash.each do |type, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3><%= t("errors.title") %>:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= t("nav_bar.home") %></a>
    </div>
    <%= form_tag "", url: projects_path, role: 'search', method: :get, class: "navbar-form navbar-left" do %>
      <div class="form-group">
        <%= text_field_tag :search, @search_term, placeholder: t("nav_bar.search"), class: "btn btn-default" %>
      </div>
    <% end %>
    <ul class="nav navbar-nav navbar-left">
      <% if cookies[:moon] %>
        <li><a href="/sun"><%= t("nav_bar.light") %></a></li>
      <%else%>
        <li><a href="/moon"><%= t("nav_bar.dark") %></a></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
        <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> <%= t("nav_bar.reg") %></a></li>
        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> <%= t("nav_bar.login") %></a></li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.username %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="/profile/<%=current_user.id%>"><%= t("nav_bar.user.profile") %></a></li>
            <li class="divider"></li>
            <li><a href="<%= destroy_user_session_url %>" data-method="delete"><%= t("nav_bar.user.exit") %></a></li>
          </ul>
        </li>
      <% end %>
      <li class="nav-item<%= " active" if I18n.locale == :ru%>">
        <%= link_to "Рус", {locale: :ru}, class: "nav-link"%>
      </li>
      <li class="nav-item<%= " active" if I18n.locale == :en%>">
        <%= link_to "Eng", {locale: :en}, class: "nav-link"%>
      </li>
    </ul>
  </div>
</nav>