config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'profile/:id', to: 'persons#profile', as: 'profile'
    get '/moon', to: 'application#moon', as: 'moon'
    get '/sun', to: 'application#sun', as: 'sun'
    get '/rating_sort', to: 'projects#rating_sort', as: 'rating_sort'
    get '/created_at_sort', to: 'projects#created_at_sort', as: 'created_at_sort'
    get '/updated_at_sort', to: 'projects#updated_at_sort', as: 'updated_at_sort'
    get '/profile/:id/give_permission', to: 'persons#give_permission', as: 'give_permission'
    get '/profile/:id/take_away_permission', to: 'persons#take_away_permission', as: 'take_away_permission'
    get '/profile/:id/ban', to: 'persons#ban', as: 'ban'
    get '/profile/:id/unban', to: 'persons#unban', as: 'unban'
    get '/profile/:id/ban_page', to: 'persons#ban_page', as: 'ban_page'
    delete '/profile/:id', to: 'persons#delete_user'
    get '/profile/:id/projects/new', to: 'persons#new_user_project', as: 'user_project_new'
    post '/profile/:id/projects', to: 'persons#create_user_project'
    get '/bonus/:bonus_id/user_bonus/create', to: 'user_bonuses#create', as: 'user_bonus_create'
    get 'projects/:project_id/transaction/new', to: 'transactions#new', as: 'new_project_transaction'
    post '/projects/:project_id/transactions', to: 'transactions#create'
    get '/add_balance/new', to: 'add_balances#new', as: 'new_add_balance'
    post '/add_balance/create', to: 'add_balances#create'
    get '/tagged', to: "projects#tagged", as: 'tagged'
    devise_for :users, skip: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }




    resources :projects do
    	resources :comments
      resources :reviews
      resources :events
    end

    resources :comments do
    	resources :likes
    end
    
    resources :project_images
    resources :bonuses


    root 'projects#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_entities
  before_action :user_is_owner, only: [:new_user_project]
  before_action :require_owner_permission, only: [:take_away_permission]
  before_action :require_admin_permission, only: [:give_permission, :ban, :unban, :delete_user, :new_user_project]
  before_action :current_user_unbanned, :current_user_banned, only: [:ban_page]

  def profile
	  @user_projects = @user.projects
  end

  def give_permission
  	@user.update(admin:true)
  	redirect_to profile_path(@user)
  end

  def take_away_permission
  	@user.update(admin:false)
  	redirect_to profile_path(@user)
  end

  def ban
  	@user.update(banned:true)
  	redirect_to profile_path(@user)
  end

  def ban_page
  end

  def unban
  	@user.update(banned:false)
  	redirect_to profile_path(@user)
  end

  def delete_user
    @user.destroy
    redirect_to root_path
  end

  def new_user_project
    @project = @user.projects.new
    @project_image = @project.project_images.build
    @project_bonuse = @project.bonuses.build
  end

  def create_user_project
    @project = @user.projects.new(params.require(:project).permit(:title,:description, :theme, :tag_list,
                                                                  :video_url, :money_need, 
                                                                  :end_date, project_images_attributes:[:id, :project_id, :image],
                                                                  bonuses_attributes:[:id, :project_id, :user_id, :name, :description, :price, :_destroy]))
    if @project.save
      if params[:project_images] != nil
        params[:project_images]['image'].each do |image|
            @project.project_images.create!(:image => image, :project_id => @project.id)
        end
      end
      flash[:success] = t("flash.persons.create_user_project")
      redirect_to project_path(@project)
    else
      render 'new_user_project'
    end
  end

  private
  	def load_entities
  		@user = User.find(params[:id])
  	end

    def current_user_banned
      if current_user.banned == true && @user != current_user
        redirect_to ban_page_path(current_user)
      end
    end

    def current_user_unbanned
      if current_user.banned == false
        redirect_to root_path
      end
    end

  	def require_admin_permission
  		if current_user.admin != true
  			redirect_to root_path
  		end
  	end

  	def require_owner_permission
  		if current_user.owner != true
  			redirect_to root_path
  		end
  	end

    def user_is_owner
      if @user.owner == true
        redirect_to root_path
      end
    end
end

app/views/persons/_bonus.html.erb
<section>
		<%= f.input :name %>
		<%= f.input :description %>
		<%= f.input :price%>
	<td>
		<%= f.input_field :_destroy, as: :hidden %>
		<%= link_to t("project.bonuses.destroy"), '#', class: 'remove_record btn btn-default' %>
	</td>
	<hr>
</section>

app/views/persons/ban_page.html.erb
<h1><%= t("person.banned") %>! :(</h1>

app/views/persons/new_user_project.html.erb
<% provide(:button_text, t("button_text.new_project")) %>
<% provide(:image_field, "new") %>
<% provide(:project_form_url, "/profile/#{@user.id}/projects") %>


<div class="container">
	<div class="project-form">
		<%= render 'shared/errors', object:@project%>
		<%= render 'projects/form' %>
	</div>
</div>

app/views/persons/profile.html.erb
<h1><%= t("profile.title") %></h1>
<%if @user.user_bonuses.any?%>
	<div class="user-bonuses scroll-bar">
		<h3><%= t("profile.user_bonuses") %></h3>
		<% @user.user_bonuses.each do |user_bonus| %>
			<section>
				<%= t("profile.user_bonus_name") %>: <%= user_bonus.bonus.name %>
			</section>
			<section>
				<%= t("profile.user_bonus_description") %>: <%= user_bonus.bonus.description %>
			</section>
			<hr>
		<% end %>
	</div>
<%end%>

<table align="center" class="table table-bordered">
		<tr>
			<th><%= t("profile.name") %>:</th>
			<td><%= @user.username %></td>
		</tr>

		<tr>
			<th><%= t("profile.email") %>:</th>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<th><%= t("profile.balance") %>:</th>
			<td>
				<%= @user.balance %> <% t("profile.currency") %> 
				<%if current_user?(@user)%>
					<%= link_to t("profile.add_balance"), new_add_balance_path, class: 'btn btn-primary' %>
				<%end%>
			</td>
		</tr>

		<%if user_admin?(current_user) && !current_user?(@user)%>
			<%if @user.admin != true%>
				<td><%= link_to t("profile.give_permission"), give_permission_path(@user), class:"btn btn-primary" %></td>
			<%elsif current_user.owner == true%>
				<td><%= link_to t("profile.take_away_permission"), take_away_permission_path(@user), class:"btn btn-primary" %></td>
			<%end%>

			<%if @user.banned != true%>
				<%if !user_owner?(@user)%>
					<td><%= link_to t("profile.ban"), ban_path(@user), class:"btn btn-danger" %></td>
				<%end%>
			<%else%>
				<td><%= link_to t("profile.unban"), unban_path(@user), class:"btn btn-primary" %></td>
			<%end%>
			<tr>
				<%if !user_owner?(@user)%>
					<td>
						<%= link_to t("profile.destroy"), "/profile/#{@user.id}", class:"btn btn-danger", data: {confirm: "#{t("profile.confirmation")} #{@user.username}"}, method: :delete %>
							
					</td>
				<%end%>
			</tr>
		<%end%>
		<%if current_user?(@user)%>
			<tr>
				<th><%= t("profile.title_edit") %></th>
				<td><%= link_to t("profile.edit"), edit_user_registration_path, class:"btn btn-default", style:"border-radius: 4px; background-color: #e7e7e7; color: black;" %></td>
			</tr>
		<%end%>
</table>

<h1><%= t("profile.projects") %></h1>
<div class="scroll-bar list">
	<table class="table table-striped">
		<% @user_projects.each do |user_project| %>
			<tbody>
				<tr> 
					<td align="center"> 
						<div data-turbolinks="false"> <%= link_to user_project.title, project_path(user_project) %> </div>
					</td>
					<% if current_user?(@user) || user_admin?(current_user) %>
						<td align="center">  <%= link_to t("profile.project.edit"), edit_project_path(user_project) %> </td>
						<td align="center">  <%= link_to t("profile.project.destroy"), user_project, method: :delete, data: {confirm: "#{t("profile.project.confirmation")}"} %> </td>
					<% end %>
				</tr>
			</tbody>
		<% end %>
	</table>
</div>
<%if current_user?(@user)%>
	<div class="text-center">
		<%= link_to t("profile.project.create"), new_project_path, class:"btn btn-primary" %>
	</div>
<%elsif user_admin?(current_user)%>
	<div class="text-center">
		<%= link_to "#{t("profile.project.create_with_user")} #{@user.username}", user_project_new_path(@user.id), class:"btn btn-primary" %>
	</div>
<%end%>