config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'profile/:id', to: 'persons#profile', as: 'profile'
    get '/moon', to: 'application#moon', as: 'moon'
    get '/sun', to: 'application#sun', as: 'sun'
    get '/rating_sort', to: 'projects#rating_sort', as: 'rating_sort'
    get '/created_at_sort', to: 'projects#created_at_sort', as: 'created_at_sort'
    get '/updated_at_sort', to: 'projects#updated_at_sort', as: 'updated_at_sort'
    get '/profile/:id/give_permission', to: 'persons#give_permission', as: 'give_permission'
    get '/profile/:id/take_away_permission', to: 'persons#take_away_permission', as: 'take_away_permission'
    get '/profile/:id/ban', to: 'persons#ban', as: 'ban'
    get '/profile/:id/unban', to: 'persons#unban', as: 'unban'
    get '/profile/:id/ban_page', to: 'persons#ban_page', as: 'ban_page'
    delete '/profile/:id', to: 'persons#delete_user'
    get '/profile/:id/projects/new', to: 'persons#new_user_project', as: 'user_project_new'
    post '/profile/:id/projects', to: 'persons#create_user_project'
    get '/bonus/:bonus_id/user_bonus/create', to: 'user_bonuses#create', as: 'user_bonus_create'
    get 'projects/:project_id/transaction/new', to: 'transactions#new', as: 'new_project_transaction'
    post '/projects/:project_id/transactions', to: 'transactions#create'
    get '/add_balance/new', to: 'add_balances#new', as: 'new_add_balance'
    post '/add_balance/create', to: 'add_balances#create'
    get '/tagged', to: "projects#tagged", as: 'tagged'
    devise_for :users, skip: :omniauth_callbacks, controllers: { omniauth_callbacks:"users/omniauth_callbacks", registrations: "users/registrations" }




    resources :projects do
    	resources :comments
      resources :reviews
      resources :events
    end

    resources :comments do
    	resources :likes
    end
    
    resources :project_images
    resources :bonuses


    root 'projects#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	after_initialize :set_defaults
	acts_as_taggable_on :tags
	belongs_to :user
  	has_many :comments, dependent: :destroy
  	has_many :project_images, dependent: :destroy
  	has_many :reviews, dependent: :destroy
 	has_many :events, dependent: :destroy
 	has_many :bonuses, dependent: :destroy
 	has_many :transactions, dependent: :destroy
  	accepts_nested_attributes_for :project_images
  	accepts_nested_attributes_for :bonuses, allow_destroy:true, reject_if: proc {|att| att[:name].blank? || att[:description].blank? || att[:price].blank?}
	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :end_date, presence: true
	validates :money_need, presence: true

	def set_defaults
	   self.money_donated = 0 if self.new_record?
	end

	def self.search_by(search_term)
		where("LOWER(title) LIKE :search_term OR LOWER(theme) LIKE :search_term", search_term: "%#{search_term.downcase}%")
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :load_entities
  before_action :require_permission, only: [:edit, :destroy]

  def index
    if cookies[:rating_sort]
      @projects = Project.includes(:reviews).order("reviews.rating desc").paginate(page: params[:page], per_page: 30)
    elsif cookies[:updated_at_sort]
      @projects = Project.order(updated_at: :desc).paginate(page: params[:page], per_page: 30)
    else
      @projects = Project.order(created_at: :desc).paginate(page: params[:page], per_page: 30)
    end

    if params[:search]
      @search_term = params[:search]
      @projects = @projects.search_by(@search_term)
    end
    @tags = ActsAsTaggableOn::Tag.all
  end

  def new
    @project = @user.projects.new
    @project_image = @project.project_images.build
    @project_bonuse = @project.bonuses.build
  end

  def create
    @project = @user.projects.new(project_params)
    if @project.save
      if params[:project_images] != nil
        params[:project_images]['image'].each do |image|
            @project.project_images.create!(:image => image, :project_id => @project.id)
        end
      end
      flash[:success] = t("flash.projects.create")
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = t("flash.projects.update")
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def show
    @comments = @project.comments.all.order("id desc").limit(10).reverse
    @events = @project.events.all
    @project_images = @project.project_images.all
    @project = Project.find(params[:id])
    @project_owner = @project.user
    @bonuses = @project.bonuses
    if user_signed_in?
      @comment = @user.comments.new
      @review = @user.reviews.new
      @user_review = @project.reviews.find_by(user_id: @user.id)
    end
  end

  def destroy
    @project.destroy
    flash[:success] = t("flash.projects.destroy")
    redirect_to profile_path(@user)
  end

  def rating_sort
    if cookies[:updated_at_sort]
      cookies.delete :updated_at_sort
    end
    cookies[:rating_sort] = {
      value:"Sort by rating"
    }
    redirect_to projects_path
  end

  def updated_at_sort
    if cookies[:rating_sort]
      cookies.delete :rating_sort
    end
    cookies[:updated_at_sort] = {
      value:"Sort by updated projects"
    }
    redirect_to projects_path
  end

  def created_at_sort
    if cookies[:rating_sort]
      cookies.delete :rating_sort
    elsif cookies[:updated_at_sort]
      cookies.delete :updated_at_sort
    end
    redirect_to projects_path
  end

  def tagged
    if params[:tag].present?
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.paginate(page: params[:page], per_page: 30)
    end
  end

  private
    def project_params
      params.require(:project).permit(:title,:description, :theme, :tag_list, 
                                      :video_url, :money_need, 
                                      :end_date, project_images_attributes:[:id, :project_id, :image], 
                                      bonuses_attributes:[:id, :project_id, :user_id, :name, :description, :price, :_destroy])
    end

    def load_entities
      @project = Project.find_by(id: params[:id])
      @user = current_user
    end

    def require_permission
      if @user.admin != true
        if current_user != Project.find(params[:id]).user
          redirect_to project_path(@project)
        end
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def current_user_has_review?
		Review.where(project_id: @project.id, user_id: current_user.id).exists?
	end

	def item_owner?(record)
		current_user == record.user
	end
end

app/views/projects/_bonus.html.erb
<section>
		<%= f.input :name %>
		<%= f.input :description %>
		<%= f.input :price %>
	<td>
		<%= f.input_field :_destroy, as: :hidden %>
		<%= link_to t("project.bonuses.destroy"), '#', class: 'remove_record btn btn-default' %>
	</td>
	<hr>
</section>

app/views/projects/_bonuses.html.erb
<% @bonuses.each do |bonus| %>
	<p>
		<section>
			<span><%= t("project.bonuses.name") %>: <%=bonus.name%></span>
		</section>
		<section>
			<span><%= t("project.bonuses.description") %>: <%=bonus.description%></span>
		</section>
		<section>
			<span><%= t("project.bonuses.price") %>: <%=bonus.price%> <%= t("project.currency") %></span>
		</section>
		<% if user_signed_in?%>
			<section>
				<% if UserBonus.where(user_id: @user.id, bonus_id: bonus.id).exists? %>
					<p><%= t("project.bonuses.status") %>!</p>
				<% else %>
					<span>
						<%= link_to t("project.bonuses.get_bonus"), user_bonus_create_path(bonus), data: {confirm: "#{t("project.bonuses.confirmation")} #{bonus.price} #{t("project.currency")}"}, class: 'btn btn-primary' %>
					</span>
				<% end %>
			</section>
		<% end %>
		<hr>
	</p>
<% end %>

app/views/projects/_form.html.erb
<%themes = ['Not chosen','Electronics','Education','Fashion','Music','Health & Beauty','Sports','Cars','Home & Garden']%>
<%=simple_form_for @project, url:yield(:project_form_url) do |f|%>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :theme, collection:themes, selected:themes[0] %>
	<%= f.input :tag_list, value: @project.send(:tag_list).to_s.downcase %>
	<%= f.input :video_url %>
	<%= f.input :money_need %>
	
	<%= f.label t("project.bonuses.title") %>
	<div class="fields">
		<%= f.fields_for :bonuses do |b| %>
			<%= render 'bonus', f: b %>
		<%end%>
	</div>
	<%= link_to_add_row(t("project.bonuses.add_bonus"), f, :bonuses, class: 'btn btn-primary') %>

	<%if yield(:image_field) == "new"%>
		<%= f.input :end_date, as: :date_time_picker, input_html:
		  { data:
		    {
		      date_format: "DD-MM-YYYY",
		      date_min_date: Time.current.strftime('%Y-%m-%d')
		    }
		  } %>
		<%= f.fields_for :project_images do |p| %>
			<div class="field">
				<%= p.label t("project.image") %>
				<%= p.file_field :image, multiple: true, name:"project_images[image][]", class:"dropzone file-upload" %>
			</div>
		<% end %>
	<% end %>
	<%= f.button :submit, yield(:button_text) , class:"btn btn-primary"%>
<% end %>

app/views/projects/edit.html.erb
<% provide(:button_text, t("button_text.edit_project")) %>
<% provide(:project_form_url, project_path(@project)) %>

<div class="container">
	<div class="project-form">
		<%= render 'shared/errors', object:@project %>
		<%= render 'form' %>
	</div>
</div>

app/views/projects/index.html.erb
<div class="container">
	<div class="main-background"></div>
		<div class="main-text">
			<h1>
				<%= t("main.title") %>
				<p> <%= t("main.description") %> </p>
			</h1>

			<h3> <%= t("main.about") %> </h3>
			<%= link_to t("main.create"), new_project_path, class:"btn btn-success" %>
		</div>
</div>

<div class="container text-center">
	<h3> <%= t("main.tags") %> </h3>
	<% @tags.each do |tag| %>
		<span class="tags">
			<%= link_to tag, tagged_path(tag: "#{tag}"), class: 'tag' %>
		</span>
	<% end %>
	<%if @projects.any?%>
		<h3> <%= t("main.projects") %>
				<div class="dropdown sort-dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				    <%= t("main.sort") %>
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="/created_at_sort"> <%= t('main.by_create_at') %> </a></li>
				    <li><a href="/updated_at_sort"><%= t("main.by_update_at") %></a></li>
				    <li><a href="/rating_sort"><%= t("main.by_rating") %></a></li>
				  </ul>
				</div>
		</h3>
		<div class="scroll-bar list">
			<table class="table table-striped">
				<tr>
					<th class="text-center"> <%= t("main.name") %> </th>
					<th class="text-center"> <%= t("main.rating") %> </th>
				</tr>
				<%= will_paginate @projects %>
				<% @projects.each do |project| %>
					<tbody>
						<tr> 
							<td> <div data-turbolinks="false"> <%= link_to project.title, project_path(project) %> </div> </td>
							<% if project.reviews.blank? %>
								<% average_rating = 0 %>
								<td> <div class="average-review-rating" data-score="<%= average_rating %>"></div> </td>
							<%else%>
								<% average_rating = project.reviews.average(:rating).round(2) %>
								<td> 
									<div class="average-review-rating" data-score="<%= average_rating %>"></div> 
								</td>
							<% end %>
						</tr>
					</tbody>
				<% end %>
			</table>
			<%= will_paginate @projects %>
		</div>
	<%end%>
</div>
<%= @review %>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'

	});
</script>

app/views/projects/new.html.erb
<% provide(:button_text, t("button_text.new_project")) %>
<% provide(:image_field, "new") %>
<% provide(:project_form_url, projects_path) %>

<div class="container">
	<div class="project-form">
		<%= render 'shared/errors', object:@project%>
		<%= render 'form' %>
	</div>
</div>

app/views/projects/show.html.erb
<%provide(:comment_form_url, project_comments_path(@project))%>

<div class="container">

	<h1><%= t("project.title") %>: <%= @project.title %></h1>
	<div style="display: block;">
		<div class="bonus-content text-center">
			<%if @bonuses.any?%>
				<h3><%= t("project.bonuses.title") %></h3>
			<%end%>
			<%= render 'bonuses' %>
		</div>
		<div class="event-content text-center">
			<%if @events.any?%>
				<h3><%= t("project.news.title") %></h3>
			<%end%>
			<%= render 'events/news' %>
		</div>
	</div>
	<h3><%= t("project.category") %>:<%= @project.theme %></h3>
	<h3><%= t("project.description") %>:<%= @project.description %></h3>
	<h3>
		<div class="tags">
			<%= t("project.tags") %>:
			<% @project.tag_list.each do |tag| %>
				<%= link_to tag, tagged_path(tag: tag), class: 'tag' %>
			<% end %>
		</div>
	</h3>
	<h3>
		<span>
			<%= t("project.donated") %>: <%= @project.money_donated %> <%= t("project.currency") %> 
			<%if user_signed_in?%>
				<%= link_to t("project.donate_button"), new_project_transaction_path(@project), class: 'btn btn-primary' %>
			<%end%>
		</span>
		<span class="project-data"><%= t("project.money_need") %>: <%= @project.money_need %> <%= t("project.currency") %></span>
	</h3>
	<% status = (@project.money_donated/@project.money_need)*100 %>
	<div class="progress" style="width: 95%;">
	  <div class="progress-bar" role="progressbar" aria-valuenow="0"
	  aria-valuemin="0" aria-valuemax="100" style="width: <%=status%>%; color:black;">
	    <%=status.round(2).to_s + "%" if status <= 100%>
	  </div>
	</div>

	<% if !@project.video_url.nil? && @project.video_url.include?("https://www.youtube.com/watch?v=")%>
		<h3><%= t("project.video") %>:</h3>
		<div align="center">
			<% video_id = @project.video_url.sub('https://www.youtube.com/watch?v=', '').split('&')[0] %>
			<iframe id="player" type="text/html" width="640" height="360"
			  src="http://www.youtube.com/embed/<%=video_id%>"
			  frameborder="0">
			</iframe>
		</div>
	<% end %>
	<h3><%= t("project.image") %></h3>
	<% @project_images.each do |pr_i| %>
		<%= image_tag(pr_i.image.url, alt: 'Image', id:"galary_image") if pr_i.image?%>
		<%if user_signed_in? && (current_user == @project_owner || user_admin?(@user))%>
			<p class="text-center" style="margin: 20px 0;">
				<%= link_to t("project.images.edit"), edit_project_image_path(pr_i), class:"btn btn-primary" %>
				<%= link_to t("project.images.destroy"), pr_i, data: {confirm: "#{t("project.images.confirmation")}"}, class:"btn btn-danger", method: :delete %>
			</p>
		<% end %>
	<% end %>

	<h3>
		<span><%= t("project.user") %>: <%= link_to @project.user.username, profile_path(@project.user.id) %></span>
		<span class="project-data"><%= t("project.end_date") %>: <%= @project.end_date  %></span>
	</h3>

	<% if user_signed_in? %>
		<p><%= render 'reviews/form' if !current_user_has_review? %></p>
		<% if @user_review != nil %>
			<div class="review-rating" data-score="<%= @user_review.rating %>"><span><%= t("project.reviews.review") %>: </span></div>
		<% end %>
	<% end %>
	
	<h4 align="center"><%= t("project.comments.title") %></h4>
	
	<div class="col">
		<div class="message-content">
			<div id="comment_update" data-project-path="<%=project_comments_path(@project)%>">
				<%= render 'comments/comment' %>
			</div>
			<% if user_signed_in? %>
				<%= render 'comments/form' %>
			<% end %>
		</div>
	</div>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

app/views/projects/tagged.html.erb
<h1><%= t("tagged.title") %>: <%= params[:tag] %></h1>
<div class="container list text-center">
	<table class="table table-striped">
		<thead>
			<th class="text-center"><%= t("tagged.name") %></th>
			<th class="text-center"><%= t("tagged.description") %></th>
		</thead>
		<%@projects.each do |project|%>	
			<tbody>	
				<tr>
					<td align="center">
						<%= link_to project.title, project_path(project) %>
					</td>
					<td align="center">
						<%=project.description%>
					</td>
				</tr>
			</tbody>
		<%end%>
	</table>
	<%= will_paginate @projects if params[:tag] == nil%>
</div>